<a href="https://colab.research.google.com/github/sreesanthrnair/My_Activity/blob/main/Numpy_Assignment_Sreesanth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Create a NumPy array with values from 10 to 49 (inclusive).
# ● Reshape it into a 4x10 matrix.
# ● Then extract the last column from the reshaped matrix -------------------------------------------------------------------------------------
import numpy as np


In [ ]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
x1=arr.reshape(4,10)
x

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
lst_column=x1[:,-1]
lst_column

array([19, 29, 39, 49])

In [ ]:
# 2.Create two 3×3 matrices:
# One filled with all 5s , One with values from 1 to 9
# ● Add the two matrices
# ● Multiply them element-wise
# ● Then find the transpose of the result
x2=np.full((3,3),5)
x2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
x3=np.arange(1,10).reshape(3,3)



In [ ]:
sum=x2+x3
sum

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
mul=x2*x3
mul

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
tranz=np.transpose(mul)
tranz

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [ ]:
#3.Create a NumPy array of 15 random integers between 10 and 100.
# ● Replace all values greater than 50 with -1
# ● Count how many values were replaced.
arr=np.random.randint(10,101,size=15)
arr

array([45, 37, 50, 55, 79, 27, 61, 84, 68, 41, 68, 38, 52, 33, 69])

In [ ]:
arr[arr>50]=-1
arr

array([45, 37, 50, -1, -1, 27, -1, -1, -1, 41, -1, 38, -1, 33, -1])

In [ ]:
count_replaced=np.sum(arr==-1)
count_replaced

np.int64(8)

In [ ]:
# 4. Generate a 5×4 array with random values between 0 and 1 (float).
# ● Find the row with the maximum sum of values.
# ● Normalize each row using the formula: --------------------------------------------------------------------
x4=np.random.random((5,4))
x4

array([[0.48569508, 0.1550692 , 0.79246515, 0.37376158],
       [0.64566344, 0.93908198, 0.13579701, 0.22585466],
       [0.14539179, 0.88887916, 0.99479276, 0.13684792],
       [0.66763663, 0.23721622, 0.16540292, 0.2810338 ],
       [0.63813754, 0.56330309, 0.50096353, 0.73601703]])

In [ ]:
row_sums = np.sum(x4, axis=1)
max_row_index = np.argmax(row_sums)
max_row = x4[max_row_index]
max_row

array([0.63813754, 0.56330309, 0.50096353, 0.73601703])

In [ ]:
min_row=np.min(x4,axis=1,keepdims=True)
max_row=np.max(x4,axis=1,keepdims=True)
normalized=(x4-min_row)/(max_row-min_row)
normalized


array([[0.51871349, 0.        , 1.        , 0.34310287],
       [0.63472672, 1.        , 0.        , 0.11211171],
       [0.00995853, 0.87654964, 1.        , 0.        ],
       [1.        , 0.14298781, 0.        , 0.23023321],
       [0.58358636, 0.26521435, 0.        , 1.        ]])

In [ ]:
# 5.arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
# # ● Find all unique elements
# # ● Find the duplicates (elements that appear more than once)
# x5=np.array([1,3,5,7,9,1,5,5])
# unique_value=np.unique(x5)
# unique_value

array([1, 3, 5, 7, 9])

In [ ]:
#5.arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#  ● Find all unique elements
#  ● Find the duplicates (elements that appear more than once)
x5 =np.array([1,3,5,3,7,9,1,5,5])
U =np.unique(x5)
U

array([1, 3, 5, 7, 9])

In [ ]:
elements, counts = np.unique(x5, return_counts=True)
duplicates = elements[counts > 1]
duplicates


array([1, 3, 5])

In [ ]:
# 6. Create a 6×6 NumPy array with values from 1 to 36.
# ● Extract the middle 4×4 submatrix.
# ● Then extract all even numbers from this submatrix.
x6=np.arange(1,37).reshape(6,6)
x6


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
submatrix=x6[1:4,1:4]
submatrix

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [ ]:
even_number=submatrix[submatrix % 2 == 0]
even_number

array([ 8, 10, 14, 16, 20, 22])

In [ ]:
#7. Generate an array of shape (3, 4) with values from 0 to 11.
# ● Reshape it to (2, 6)
# ● Then flatten it into a 1D array
# ● Convert the 1D array back to shape (4, 3)

x7=np.arange(0,12).reshape(3,4)
x7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
reshape_it=x7.reshape(2,6)
reshape_it

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
flattened=reshape_it.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 8.Create an array: a = np.array([[1, 2], [3, 4]])
# ● Append a new row [5, 6]
# ● Then append a new column [7, 8, 9]

a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
new = np.array([[5, 6]])
new_row = np.append(a, new, axis=0)
new_row
newc = np.array([7, 8, 9]).reshape(3, 1)
new_col = np.append(new_row, newc, axis=1)
display(new_col)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [ ]:
#9. a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# c = np.array([7, 8, 9])
# ● Join them into a single array
# ● Reshape the result into a 3×3 matrix
# ● Extract the diagonal elements

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined=np.concatenate((a,b,c))
joined

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matrix = joined.reshape(3, 3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
diagonal_elements = np.diag(matrix)
diagonal_elements

array([1, 5, 9])

In [ ]:
#10. Create a NumPy array of integers from 1 to 20.
# ● Extract all values that are divisible by 3 or 5.
# ● Count how many such values exist.

x8=np.arange(1,21)
x8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
divisible=x8[(x8 % 3 == 0) | (x8 % 5 == 0)]
divisible


array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [ ]:
count=len(divisible)
count

9